checks:
  php: true
filter:
  excluded_paths:
    - 'tests/*'
build:
  environment:
    php:
      version: 7.4
coverage:
  - command: vendor/bin/phpunit --coverage-clover coverage.xml
    coverage:
      file: coverage.xml
      format: clover
