build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev "squizlabs/php_codesniffer=3.6.2"
  environment:
    php:
      version: 8.0
    mysql:
      version: 5.7
  dependencies:
    before:
      - mysql -uroot -e 'CREATE DATABASE testing'
