filter:
  paths:
    - 'app/*'
    - 'src/*'
  excluded_paths:
    - 'bootstrap/*'
    - 'config/*'
    - 'public/*'
    - 'resources/*'
    - 'vendor/*'
    - 'views/*'
build:
  environment:
    php:
      version: 7.4
    mysql:
      version: 5.7
