build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.4
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
