preset: laravel

enabled:
  - alpha_ordered_imports

disabled:
  - length_ordered_imports
  -
finder:
  exclude:
    - tests
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name:
    - index.php
    - server.php
    - "*.blade.php"
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"
