php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
#    - unused_use
#    - phpdoc_summary
  finder:
    not-name:
      - index.php
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
